pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND' 
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages {
        stage('Init') {
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 100-cdn
                        terraform init -reconfigure
                        terraform plan -out tfplan
                    """
                }
                 
               }
            }
        }
        stage('Apply') {
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            // }
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 100-cdn
                        if [ ${params.ACTION} == 'apply' ]
                            then
                                terraform apply -auto-approve tfplan
                            elif [ ${params.ACTION} == 'destroy' ]
                            then
                                terraform destroy -auto-approve
                        fi
                    """
                }
                 
               }
            }
        }

        stage('Destroy'){
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    script {
                        def directories = ['100-cdn', '60-ingress-alb', '50-acm', '41-ecr', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
                        for (dir in directories) {
                            echo "Destroying resources in directory: ${dir}"
                            sh """
                            cd ${dir}
                            terraform init -reconfigure
                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
                            cd ..
                            """
                        }
            }
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}